### ISSUE TITLE
CF: Controlling "Universal SSL" option

### ISSUE THREAD

**Issue by patschi** [StackExchange/dnscontrol#494]
I'd like to have a option to control the "Universal SSL" option of Cloudflare, just like with the proxy setting. The reason is following: I'd like to use Cloudflare as a DNS provider for a few domains, but CF shouldn't issue any certificates for these.

While I'm able to manually disable that specific setting, it is still much more convenient to handle that in an automated way with dnscontrol, and also integrates in a nice way when using `dnscontrol create-domains`.

Are there any voices against adding something like `CF_UNIVERAL_SSL('off')`?

**Comment by tlimoncelli** [comment]
Sounds good to me!

**Comment by patschi** [comment]
I've filed #496 and just wanted to update the (annoying) `static.go` file so that it can be merged again... however I'm getting some strange error and I've currently no clue what's the exact issue. Must have something to do that it's Monday morning.

```
pkernstock@PKERNSTOCK-SB2:/mnt/c/dev/gh-dnscontrol$ rm $GOPATH/go/src/github.com/StackExchange/dnscontrol/ -Rf
pkernstock@PKERNSTOCK-SB2:/mnt/c/dev/gh-dnscontrol$ go generate
build/generate/featureMatrix.go:9:2: cannot find package "github.com/StackExchange/dnscontrol/providers" in any of:
        /usr/lib/go-1.11/src/github.com/StackExchange/dnscontrol/providers (from $GOROOT)
        /home/pkernstock/go/src/github.com/StackExchange/dnscontrol/providers (from $GOPATH)
build/generate/featureMatrix.go:10:2: cannot find package "github.com/StackExchange/dnscontrol/providers/_all" in any of:
        /usr/lib/go-1.11/src/github.com/StackExchange/dnscontrol/providers/_all (from $GOROOT)
        /home/pkernstock/go/src/github.com/StackExchange/dnscontrol/providers/_all (from $GOPATH)
main.go:14: running "go": exit status 1
pkernstock@PKERNSTOCK-SB2:/mnt/c/dev/gh-dnscontrol$ go get github.com/StackExchange/dnscontrol
pkernstock@PKERNSTOCK-SB2:/mnt/c/dev/gh-dnscontrol$ go generate
# command-line-arguments
build/generate/generate.go:18:11: not enough arguments in call to embed.Run
        have (*embed.Config)
        want (*embed.Config, io.Writer)
main.go:14: running "go": exit status 2
```

Do you have any idea, @tlimoncelli? As there were no changes to the `generate.go` file in the last two years, it must be something wrong with my setup, but I can't spot any reason.

I can swear that it worked with Go 1.11 a few weeks ago.

**Comment by tlimoncelli** [comment]
I'm not at my dev PC right now so this might not be useful advice but...

Can you try go1.12.4?  Also, the "-rf" flags to "rm" need to be immediately after the command.

**Comment by patschi** [comment]
go1.12 won't work neither:
```
pkernstock@PKERNSTOCK-SB2:/mnt/c/dev/gh-dnscontrol$ go version
go version go1.12 linux/amd64
pkernstock@PKERNSTOCK-SB2:/mnt/c/dev/gh-dnscontrol$ go generate
# command-line-arguments
build/generate/generate.go:18:11: not enough arguments in call to embed.Run
        have (*embed.Config)
        want (*embed.Config, io.Writer)
main.go:14: running "go": exit status 2
```

> Also, the "-rf" flags to "rm" need to be immediately after the command.

Nope, you can also use the parameters at the end. I often realize that I'd like to delete a non-empty folder when I've already auto-completed the rm-command, so I just append `-Rf` at the end.

**Comment by tlimoncelli** [comment]
rm:  Ugh, another GNUism that would make Dennis Ritchie cry.

Anyway...

about go generate:  I'm having trouble reproducing the issue.   I'm at 8b86eec6bfde28b782655f54f99352ba068340c3 (recently rebased to master).  I've tried go1.12 and go1.12.4. No luck.

Could you try it on another machine?

What OS are you on?

Tom

**Comment by patschi** [comment]
I'm running Windows 10 1809, using WSL. However I was able to fix it. The issue was that the dnscontrol project wasn't within `$GOROOT`.

My guess is: When the project is within `$GOROOT`, it does use the `vendor/` folder - so everything works fine as expected. But when it isn't, the `vendor/` folder is being ignored (for unknown reasons) and causes a version conflict of the `mjibson/esc/embed` Go library. So there seems to be a breaking change in said library in a later, more recent release.

Thanks a lot for your help!

**Comment by captncraig** [comment]
Specifically, the repo should be checked out to `$GOPATH/src/github.com/stackexchange/dnscontrol`

Its a pain, I know, but that's how go projects really demand to be handled.
