### ISSUE TITLE
Possible bug introduced by #3775 with Namecheap provider; Zone "xxx" does not exist ...

### ISSUE THREAD

**Issue by ajkavanagh** [StackExchange/dnscontrol#3824]
**Describe the bug**

I *think* that #3775 may have introduced a bug in the namecheap provider.  With 4.25.0 it works correctly, but with 4.26.0 it says:

*Note I've switch my domain name for 'example.com' in this bug, but I was using my domain name*

```text
 $ dnscontrol preview --creds "./creds.sh" --config "./dnsconfig.js" --domains example.com
CONCURRENTLY checking for 1 zone(s)
SERIALLY checking for 0 zone(s)
Waiting for concurrent checking(s) to complete...DONE
******************** Domain: example.com
1 correction (namecheap)
INFO#1: Zone "example.com" does not exist. Can not create because "namecheap" does not implement ZoneCreator
CONCURRENTLY gathering records of 1 zone(s)
SERIALLY gathering records of 0 zone(s)
Waiting for concurrent gathering(s) to complete...DONE
******************** Domain: tulipgirl.uk
Done. 1 corrections.
completed with errors
```

Whereas with 4.25.0:

```text
# dnscontrol preview --creds "./creds.sh" --config "./dnsconfig.js" --domains example.com
CONCURRENTLY checking for 1 zone(s)
SERIALLY checking for 0 zone(s)
Waiting for concurrent checking(s) to complete...DONE
CONCURRENTLY gathering records of 1 zone(s)
SERIALLY gathering records of 0 zone(s)
Waiting for concurrent gathering(s) to complete...DONE
******************** Domain: example.com
Done. 0 corrections.
```

*Note I've switch my domain name for 'example.com'.*

**Expected behavior**

I expected that 4.26.0 would work like 4.25.0.  The domain 

**DNS Provider**
 
Namecheap

**Comment by ajkavanagh** [comment]
Thanks for looking at this.

In answer to your questions:

> Does the domain exist at namecheap?

Yes, the domain does exist.

> The output of the command:

So I ran:

```text
dnscontrol get-zones --creds="./creds.sh" --format=nameonly namecheap  - all
```

And got back a list of all the domains *except* the one I was looking for!  So some additional information:

1. The domain I was expecting is the last one in the list on the namecheap dashboard.  It is also alphabetically the last domain.
2. The get-zones command lists the zones alphabetically.
3. The count of the zones returned (using `| wc -l`) is 20.
4. I have 26 zones at namecheap, so it looks like *6 zones* are missing from get-zones.

I wondered if it is possible that the `get-zones` command has a limit on the zones it replies at namecheap for a single call.

Looking at https://www.namecheap.com/support/api/methods/domains/get-list/ it looks like the default `pageSize` is 20, which concurs with the above listing provided.  Maybe it's something to do with needing to fetch more than one page?

**Comment by tlimoncelli** [comment]
CC @willpower232 

I don't have access to Namecheap, so the fix will have to come from the community.

**Comment by tlimoncelli** [comment]
Whatever you think is best (sending a PR to the third party library, forking it, etc).  

Publishing a package in Go is easy.  If its on github, it's published.
